# -*- coding: utf-8 -*-
"""
/***************************************************************************
 seasonDistance
                                 A QGIS plugin
 Calculates Owls Season Distance
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-07-09
        copyright            : (C) 2018 by University of Muenster
        email                : b_teka02@uni-muenster.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load seasonDistance class from file seasonDistance.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .owls_season_distance import seasonDistance
    return seasonDistance(iface)
